### ISSUE TITLE
用别的端口启动，网页内的链接指向都不对

### ISSUE THREAD

**Issue by think2011** [hylin/apifaker#2]
如图所示，因为80端口被占用了，所以我用的端口别的，但是里面资源都还是指向80端口的，所以出错了。

![](http://ntu.me/di/UW092/QQ截图20140815160952.png)

**Comment by think2011** [comment]
我通过修改 config.js 的设置修复好了。

还有一个问题就是
- 支持同一接口根据不同参数，返回不同模拟数据

这个特性我不知道如何操作，能大概指个方向吗？

**Comment by hylin** [comment]
点击接口列表-操作列的 “模拟" 按钮，然后新页面中点击 "增加模拟数据"，填入各个参数值，和返回内容，就完成一条模拟数据。重复添加不同的参数值的模拟数据就可以了。

**Comment by think2011** [comment]
@hylin 谢谢！我试试！
