### ISSUE TITLE
添加模拟数据时不太方便输入

### ISSUE THREAD

**Issue by wzshuang** [hylin/apifaker#4]
只能修改右边的，然后同步到左边去。能不能使左边的不要限制，直接可以修改？
![qq 20150413150352](https://cloud.githubusercontent.com/assets/8585771/7111137/52fd79f2-e1ee-11e4-93c1-0a51f5c644ea.png)
例如，我想在左边的data数组里添加数据，这时只能从右边添加，很不方便。

**Comment by hylin** [comment]
左边也可以修改的，只是必须是标准的json格式，比如引号必须是双引号

**Comment by wzshuang** [comment]
不知道是不是浏览器兼容性问题，我在谷歌下使用时，左边很难在光标处输入修改内容，总是替换掉光标处的字符，修改起来很不便。
anyway，最近的项目用到了这个工具，帮了很大的忙，非常感谢^_^
